package main

import (
	"testing"

	"gotest.tools/v3/assert"
)

func TestGenerateStatus(t *testing.T) {
	cases := []struct {
		name      string
		title     string
		artist    string
		album     string
		albumMode bool
		loved     bool
		expected  string
	}{
		{
			name:     "track mode/short",
			artist:   "The B-52s",
			title:    "Rock Lobster",
			album:    "The B-52s",
			expected: "The B-52s - Rock Lobster",
		},
		{
			name:     "loved",
			artist:   "The B-52s",
			title:    "Rock Lobster",
			album:    "The B-52s",
			loved:    true,
			expected: "The B-52s - Rock Lobster :heart:",
		},
		{
			name:      "album mode/short",
			artist:    "Pixies",
			title:     "Monkey Gone To Heaven",
			album:     "Doolittle",
			albumMode: true,
			expected:  "Pixies - Doolittle",
		},
		{
			name:      "long",
			artist:    "Coheed and Cambria",
			title:     "Ten Speed (Of God's Blood & Burial)",
			album:     "Good Apollo I'm Burning Star IV Volume One: From Fear Through The Eyes Of Madness",
			albumMode: true,
			expected:  "Coheed and Cambria - Good Apollo I'm Burning Star IV Volume One: From Fear Through The Eyes Of Ma...",
		},
		{
			name:      "long and loved",
			artist:    "Coheed and Cambria",
			title:     "Ten Speed (Of God's Blood & Burial)",
			album:     "Good Apollo I'm Burning Star IV Volume One: From Fear Through The Eyes Of Madness",
			albumMode: true,
			loved:     true,
			expected:  "Coheed and Cambria - Good Apollo I'm Burning Star IV Volume One: From Fear Through The Ey... :heart:",
		},
		{
			name:   "artist _and_ title long",
			artist: "Acidic Vaginal Liquid Explosion Generated by Mass Amounts of Filthy Fecal Fisting and Sadistic Septic Syphilic Sodomy Inside the Infected Maggot Infested Womb of a Molested Nun Dying Under the Roof of a Burning Church While a Priest Watches and Ejaculates in Immense Perverse Pleasure over His First Fresh Fetus",
			title:  "Pneumonoultramicroscopicsilicovolcanoconiosis",
			album:  "Gore 2.0",
			// 100 - 3( - ) = 97
			// artist = 311 -> 311 / (311+45) = 87.4%
			// title = 45 / (311+45) 12.6%
			// floor(87.4% * 97) => 84
			// 97-84 = 13
			expected: "Acidic Vaginal Liquid Explosion Generated by Mass Amounts of Filthy Fecal Fisting... - Pneumonoul...",
		},
		{
			name:   "artist _and_ title long _and_ loved",
			artist: "Acidic Vaginal Liquid Explosion Generated by Mass Amounts of Filthy Fecal Fisting and Sadistic Septic Syphilic Sodomy Inside the Infected Maggot Infested Womb of a Molested Nun Dying Under the Roof of a Burning Church While a Priest Watches and Ejaculates in Immense Perverse Pleasure over His First Fresh Fetus",
			title:  "Pneumonoultramicroscopicsilicovolcanoconiosis",
			album:  "Gore 2.0",
			loved:  true,
			// 100 - 3( - ) - 8( :heart:) = 89
			// floor(87.4% * 89) => 77
			// 89 - 77 => 12
			// also trims the space after Fecal
			expected: "Acidic Vaginal Liquid Explosion Generated by Mass Amounts of Filthy Fecal... - Pneumonou... :heart:",
		},
		{
			name:     "minimum 9",
			artist:   "Acidic Vaginal Liquid Explosion Generated by Mass Amounts of Filthy Fecal Fisting and Sadistic Septic Syphilic Sodomy Inside the Infected Maggot Infested Womb of a Molested Nun Dying Under the Roof of a Burning Church While a Priest Watches and Ejaculates in Immense Perverse Pleasure over His First Fresh Fetus",
			title:    "Gore",
			album:    "Gore 2.0",
			loved:    true,
			expected: "Acidic Vaginal Liquid Explosion Generated by Mass Amounts of Filthy Fecal Fisting... - Gore :heart:",
		},
		{
			name:   "minimum 9 even if both truncated",
			artist: "Acidic Vaginal Liquid Explosion Generated by Mass Amounts of Filthy Fecal Fisting and Sadistic Septic Syphilic Sodomy Inside the Infected Maggot Infested Womb of a Molested Nun Dying Under the Roof of a Burning Church While a Priest Watches and Ejaculates in Immense Perverse Pleasure over His First Fresh Fetus",
			title:  "Smokebreak",
			album:  "Gore 2.0",
			loved:  true,
			// artist = 311 -> floor(311 / (311+10) * 89) = 86
			// title = 89 - 86 = 3. min 9
			// artist = 89 - 9 = 80
			expected: "Acidic Vaginal Liquid Explosion Generated by Mass Amounts of Filthy Fecal Fis... - Smokeb... :heart:",
		},
	}
	for _, test := range cases {
		t.Run(test.name, func(t *testing.T) {
			*AlbumMode = test.albumMode
			actual := GenerateStatus(test.title, test.artist, test.album, test.loved)
			assert.Equal(t, test.expected, actual)
			assert.Assert(t, len(actual) <= MaxLength, "exceeds max length")
		})
	}
}

// Iwrestledabearonce
